### ISSUE TITLE
Add random() wrapper

### ISSUE THREAD

**Issue by AlphaRLee** [Schulich-Ignite/spark#36]
Slides team uses this in Session 3 for a pong exercise to start the ball in a random direction. It's not mandatory to have but would be nice

Acceptance Criteria:
* [x] Add `random()` that returns a float r, `0 <= r <= 1.0`
* [x] Add `randint(n)` that returns an int r, `0 <= r < n `
* [x] Add to documentation

**Comment by lawruble13** [comment]
Resolved in #47.
