### ISSUE TITLE
Cast numbers in parse_color to ints automatically

### ISSUE THREAD

**Issue by AlphaRLee** [Schulich-Ignite/spark#43]
Currently, when students attempt to enter a float into `fill_style`, `stroke_style`, etc. they face an int casting error (e.g. error thrown when typing `fill_style(123.45, 0, 0)`. Students shouldn't need to be burdened with knowing `int()` to get this working.

AC:
  * [x] Alter `parse_color` to accept floats and cast any floats to ints
  * [x] Alter decorators (if in use) on `fill_style`, `stroke_style`, `background` and anything else using `parse_color` to allow for floats (dependent on PR #42 being merged in)
  * [x] Update docs (no need to explicitly mention this, just change function signature as necessary)
  * [x] Bump version number

**Comment by lawruble13** [comment]
Resolved in main in #47 .
