### ISSUE TITLE
Key events

### ISSUE THREAD

**Issue by AlphaRLee** [Schulich-Ignite/spark#55]
```py
# Syntax option 1
if key_held['a'] and key_held['b']:

end
```

AC:
 * [x] Add a user-definable `key_pressed()` function
    * If no key functions are defined, the event handlers should *not* be created, as they will slow down the program unnecessarily
 * [x] Filter out repeated key pressed
    * The user-defined `key_pressed` should only be called once when the key goes from not pressed to pressed
 * [x] Add a user-definable `key_released()` function
    * The user-defined `key_released` should only be called once when the key goes from pressed to not pressed
 * [x] OPTIONAL - add a user-definable `key_repeated()` function
    * The user-defined `key_repeated` should be called each time the browser re-issues the key pressed event, which will occur when the key is held
 * [x] Add `key_held` dict to detect if a key is held, necessary for diagonal movement (see code sample above)
    * Should be a global immutable dictionary, for each key the value is whether that key is currently pressed or not
 * [x] When a special key (e.g. arrow key) is pressed, make it detectable by `key` (unlike Processing that uses `keyCode` to distinguish)
 * [x] Unit tests
   * [x] Must include a "game" example where a player can travel diagonally by pressing 2 keys simultaneously
 * [x] Assign @Descent098 to this ticket when ready to start documentation and communicate how it works
 * [x] Document regular key presses
 * [x] Document special keys
 * [x] Document key pressed events

**Comment by lawruble13** [comment]
Question: if the user presses the `'a'` key while shift is held, do we want to register that as `'A'` or `'a'`?

**Comment by AlphaRLee** [comment]
I'm ok registering this as `'A'`, since that's consistent with Processing. Do you know how HTML handles this natively?

**Comment by lawruble13** [comment]
There's actually two different things which record the key that was pressed, one of which does the appropriate capitalization, and the other which would just give `'KeyA'` for both. The shift key is also separately recorded. The latter method is what I'll be using for special keys, and in my earlier testing I found the former method to be inconsistent.

**Comment by AlphaRLee** [comment]
Ah, that's fine if you want to have this appear as `'a'` then, especially since if students want to be using capital letters, they probably should be learning about how to use special characters in the first place.

**Comment by lawruble13** [comment]
Sounds good, I'll register it that way then.

**Comment by lawruble13** [comment]
Having re-investigated, I think delivering the appropriate capitalization is pretty easy, and the inconsistency I had seen was due to keyboard mapping. Given that, I think returning `'A'` is easier, more correct, and more accurately reflects what they'd see if they were doing event handling directly.
