### ISSUE TITLE
Tech Debt: Move helper functions to different file

### ISSUE THREAD

**Issue by raduschirliu** [Schulich-Ignite/spark#56]
AC:
 * [x] Create a method by which helper functions can be added to the Core object, while the function body is elsewhere
 * [x] Move the body of existing helper functions to other locations
    * This should be done in such a fashion that merges can be performed easily
 * [x] Add documentation for developers

**Comment by Descent098** [comment]
I won't have time tonight to write the docs for this, is it fine to be completed tomorrow? If need be the docs can be moved straight into main since it's in the new CONTRIBUTING file anyway so this shouldn't block the open PR.

**Comment by lawruble13** [comment]
I don't think it's particularly urgent, so tomorrow should be fine.
