### ISSUE TITLE
Add watchdog on cells running Python code

### ISSUE THREAD

**Issue by AlphaRLee** [Schulich-Ignite/spark#79]
When students kick off an infinite while loop, they can hang the program

AC:
 * [ ] Kill thread if a student runs a task for more than 10 seconds (e.g. single draw() execution takes too long)
 * [ ] Look into making a daemon thread to kill draw() when the main thread dies
 * [ ] Unit tests
 * [ ] Docs are nice-to-have, not required in detail

**Comment by ckski** [comment]
According to Python documentation for the threading module (https://docs.python.org/3.8/library/threading.html):
> Python’s Thread class supports a subset of the behavior of Java’s Thread class; currently, there are no priorities, no thread groups, and threads **cannot be destroyed, stopped, suspended, resumed, or interrupted**.

**Comment by AlphaRLee** [comment]
WONTFIX: This is an issue for the back-end/platform to handle, not Library
